// src/components/home/contact/contact-form.component.tsx
import classNames from 'classnames/bind'
import { useRef, useState, type FC, type FormEvent } from 'react'
import { Button } from '../../core/button/button.component'
import css from './contact-form.module.css'

const classes = classNames.bind(css)

export const ContactForm: FC = () => {
  const [isLoading, setIsLoading] = useState(false)
  const [showErrorMessage, setShowErrorMessage] = useState(false)
  const [showSuccessMessage, setShowSuccessMessage] = useState(false)
  const form = useRef<HTMLFormElement>(null)

  const onSubmit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault()
    setIsLoading(true)
    setShowErrorMessage(false)

    try {
      const formData = new FormData(form.current!)
      const response = await fetch('https://formspree.io/f/mnqlpdwk', {
        method: 'POST',
        body: formData,
        headers: {
          Accept: 'application/json',
        },
      })

      if (!response.ok) {
        showError()
        return
      }

      setShowSuccessMessage(true)
    } catch (_) {
      showError()
    }
  }
  function showError() {
    setIsLoading(false)
    setShowErrorMessage(true)
  }

  return (
    <form className={classes('contact-form')} onSubmit={onSubmit} ref={form}>
      <label htmlFor="name">Nombre</label>
      <input id="name" name="name" type="text" required />

      <label htmlFor="email">Correo electrónico</label>
      <input id="email" name="_replyto" type="email" required />

      <label htmlFor="message">Mensaje</label>
      <textarea id="message" name="message" rows={5} minLength={5} required></textarea>
      {showErrorMessage && (
        <p className={classes('error-message')}>Algo no ha salido bien, por favor vuelve a intentarlo.</p>
      )}

      {showSuccessMessage ? (
        <p className={classes('success-message')}>Mensaje enviado. ¡Muchas gracias por conectar! 😊</p>
      ) : (
        <Button id="submit-button" type="submit" isLoading={isLoading}>
          Enviar
        </Button>
      )}
    </form>
  )
}

// components/ui/home/ContactForm.vue
<template>
  <div id="contacto" class="xl-container p-8">
    <Heading type="h2" text="contacto" class="mb-4 xl:mb-8" />
    <form v-if="!formSent" ref="contactForm" @submit.prevent="sendForm">
      <h3 class="text-lg mb-2">nombre</h3>
      <input
        v-model="nameValue"
        name="name"
        type="text"
        required
        class="w-full lg:w-1/3"
      />

      <h3 class="text-lg mt-6 mb-2">correo electrónico</h3>
      <input
        v-model="emailValue"
        name="_replyto"
        type="email"
        required
        class="w-full lg:w-1/3"
      />

      <h3 class="text-lg mt-6 mb-2">mensaje</h3>
      <textarea
        v-model="messageValue"
        name="message"
        required
        class="w-full xl:w-1/2"
      ></textarea>

      <Button
        class="mt-6"
        :type="inProgress ? 'outline' : 'primary'"
        @btn-clicked="sendForm"
      >
        {{ inProgress ? 'enviando' : 'enviar' }}
      </Button>
      <span v-if="hasError" class="text-sm text-red-600"
        >Lo siento, no he podido enviar el formulario. Inténtalo otra vez.</span
      >
    </form>
    <h3 v-else>👌 Muchas gracias por contactar conmigo.</h3>
  </div>
</template>

<script>
const actionForm = 'https://formspree.io/f/mnqlpdwk'

export default {
  name: 'ContactForm',
  data() {
    return {
      nameValue: '',
      emailValue: '',
      messageValue: '',
      formSent: false,
      inProgress: false,
      hasError: false,
    }
  },
  methods: {
    async sendForm() {
      if (this.inProgress) return
      if (!this.emailValue || !this.messageValue) {
        this.hasError = true
        return
      }

      this.hasError = false
      this.inProgress = true
      try {
        const response = await fetch(actionForm, {
          method: 'POST',
          body: JSON.stringify({
            name: this.nameValue,
            _replyto: this.emailValue,
            message: this.messageValue,
          }),
          headers: {
            Accept: 'application/json',
          },
        })

        if (response.ok) {
          this.inProgress = false
          this.formSent = true
        }
      } catch (error) {
        this.inProgress = false
        this.hasError = true
      }
    },
  },
}
</script>
